import jsPDF from "jspdf";

export function generatePDFReport(analysis: any, fileName: string = "Legal_Analysis_Report.pdf") {
    const doc = new jsPDF();
    const margin = 20;
    const pageWidth = doc.internal.pageSize.getWidth();
    let y = 20;

    // Title
    doc.setFontSize(22);
    doc.setTextColor(59, 130, 246); // Primary blue
    doc.text("LegalLens AI Analysis", margin, y);
    y += 10;

    // File Name
    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text(`Document: ${fileName}`, margin, y);
    y += 15;

    // Summary
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text("Executive Summary", margin, y);
    y += 7;
    doc.setFontSize(11);
    const summaryLines = Array.isArray(analysis.summary) ? analysis.summary : [analysis.summary];
    summaryLines.forEach((item: any) => {
        const splitText = doc.splitTextToSize(`• ${item}`, pageWidth - (margin * 2));
        doc.text(splitText, margin, y);
        y += splitText.length * 5;
    });
    y += 5;

    // Risks (Red)
    doc.setFontSize(16);
    doc.setTextColor(220, 38, 38); // Red
    doc.text("Critical Risks", margin, y);
    y += 7;
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    const riskLines = Array.isArray(analysis.risks) ? analysis.risks : [analysis.risks];
    riskLines.forEach((item: any) => {
        const splitText = doc.splitTextToSize(`! ${item}`, pageWidth - (margin * 2));
        doc.text(splitText, margin, y);
        y += splitText.length * 5;
    });
    y += 10;

    // Simplified Version
    doc.setFontSize(16);
    doc.setTextColor(5, 150, 105); // Green
    doc.text("Simplified Breakdown", margin, y);
    y += 7;
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    const simplifiedLines = doc.splitTextToSize(analysis.simplified_version || "N/A", pageWidth - (margin * 2));
    doc.text(simplifiedLines, margin, y);
    y += simplifiedLines.length * 5;

    // Footer
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by LegalLens AI - Confidential", margin, pageHeight - 10);

    doc.save(fileName.replace(/\.[^/.]+$/, "") + "_Analysis.pdf");
}
